[theme]
base = "light"
primaryColor = "#A665BD"
backgroundColor = "#FCF9FD"
secondaryBackgroundColor = "#F2EAF5"
textColor = "#35273B"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
