[theme]
base = "light"
primaryColor = "#B96891"
backgroundColor = "#F7F1F4"
secondaryBackgroundColor = "#F0E4E9"
textColor = "#442D37"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
